StoryWriting_n01304390/Models/Story.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace StoryWriting_n01304390.Models
{
    // The model for a single story
    // Has a story id, title, description, creator, a flag specifying whether or not it has a feature image, and the image type
    // A story can link to one creator but multiple story contents
    public class Story
    {
        [Key]
        public int StoryID { get; set; }

        [Required, StringLength(255), Display(Name = "Story Title")]
        public string StoryTitle { get; set; }

        [Required, StringLength(255), Display(Name = "Story Description")]
        public string StoryDescription { get; set; }

        public virtual Writer StoryCreator { get; set; }

        public virtual ICollection<StoryContent> StoryContents { get; set; }

        public bool HasFeatureImage { get; set; }

        public string ImageType { get; set; }
    }
}

StoryWriting_n01304390/Controllers/StoryContentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using StoryWriting_n01304390.Models;
using StoryWriting_n01304390.Models.ViewModels;

namespace StoryWriting_n01304390.Controllers
{
    public class StoryContentController : Controller
    {
        private StoryWritingDbContext database = new StoryWritingDbContext();

        // Should be no default view for StoryContent, redirect to GetList view for Story
        public ActionResult Index()
        {
            return RedirectToAction("GetList", "Story");
        }

        // Sends a viewmodel to the AddContent view for StoryContent and returns the view
        // A viewmodel is used because the view needs information about both the story the content is being 
        // added to, and a list of all the writers in the database
        public ActionResult AddContent(int? id)
        {
            if ((id == null) || (database.Stories.Find(id) == null))
            {
                return HttpNotFound();
            }

            AddOrEditViewModel addContentView = new AddOrEditViewModel();
            addContentView.Story = database.Stories.Find(id);
            addContentView.Writers = database.Writers.ToList();

            return View(addContentView);
        }

        // This runs after the user submits a form to add the story content in the AddContent view
        // Add the story content and redirect back to the ViewStory view for the Story specified by id
        [HttpPost]
        public ActionResult Create(int? id, string new_story_content, string new_content_writer)
        {
            if ((id == null) || (database.Stories.Find(id) == null))
            {
                return HttpNotFound();
            }

            string queryString = "INSERT INTO storycontents (Content, ContentWriter_WriterID, Story_StoryID) VALUES (@content, @writer, @story)";

            SqlParameter[] queryParams = new SqlParameter[3];
            queryParams[0] = new SqlParameter("@content", new_story_content);
            queryParams[1] = new SqlParameter("@writer", new_content_writer);
            queryParams[2] = new SqlParameter("@story", id);

            database.Database.ExecuteSqlCommand(queryString, queryParams);

            return RedirectToAction("ViewStory/" + id, "Story");
        }

        // Sends a viewmodel to the EditContent view for StoryContent and returns the view
        // A viewmodel is used because the view needs information about both the story the content is being 
        // edited from, and a list of all the writers in the database
        public ActionResult EditContent(int? id)
        {
            if ((id == null) || (database.StoryContents.Find(id) == null))
            {
                return HttpNotFound();
            }

            AddOrEditViewModel editContentView = new AddOrEditViewModel();
            editContentView.StoryContent = database.StoryContents.Find(id);
            editContentView.Writers = database.Writers.ToList();

            return View(editContentView);
        }

        // This runs after the user submits a form to edit the story content in the EditContent view
        // Edit the story content and redirect back to the ViewStory view for the Story specified by 
        // the id of the story being edited
        [HttpPost]
        public ActionResult Update(int? id, string new_story_content, string new_content_writer)
        {
            if ((id == null) || (database.StoryContents.Find(id) == null))
            {
                return HttpNotFound();
            }

            string query = "UPDATE storycontents SET Content=@content, ContentWriter_WriterID=@writer WHERE StoryContentID=@contentid";

            SqlParameter[] queryParams = new SqlParameter[3];
            queryParams[0] = new SqlParameter("@content", new_story_content);
            queryParams[1] = new SqlParameter("@writer", new_content_writer);
            queryParams[2] = new SqlParameter("@contentid", id);

            database.Database.ExecuteSqlCommand(query, queryParams);

            return RedirectToAction("ViewStory/" + database.StoryContents.Find(id).Story.StoryID, "Story");
        }

        // Delete the specific story content corresponding to id
        // Returns the ViewStory view for Story corresponding to the story the content was linked to
        public ActionResult DeleteContent(int? id)
        {
            if ((id == null) || (database.StoryContents.Find(id) == null))
            {
                return HttpNotFound();
            }

            var storyID = database.StoryContents.Find(id).Story.StoryID;

            string queryString = "DELETE FROM storycontents WHERE StoryContentID=@scontentid";
            SqlParameter param = new SqlParameter("@scontentid", id);

            database.Database.ExecuteSqlCommand(queryString, param);

            return RedirectToAction("ViewStory/" + storyID, "Story");
        }
    }
}

StoryWriting_n01304390/Controllers/StoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using StoryWriting_n01304390.Models;
using StoryWriting_n01304390.Models.ViewModels;
using System.IO;

namespace StoryWriting_n01304390.Controllers
{
    public class StoryController : Controller
    {
        private StoryWritingDbContext database = new StoryWritingDbContext();

        // Default View for Story, redirect to the GetList View
        public ActionResult Index()
        {
            return RedirectToAction("GetList");
        }

        // Send a list of all stories to the GetList View for Story and returns the view
        public ActionResult GetList()
        {
            IEnumerable<Story> stories = database.Stories.ToList();
            return View(stories);
        }

        // Send a list of all writers to the AddStory view for Story (used to generate the dropdown list) and return the view
        public ActionResult AddStory()
        {
            IEnumerable<Writer> writers = database.Writers.ToList();
            return View(writers);
        }

        /* This runs after the user submits the form to add a story in the view, add the story to the database
            and redirect back to the GetList view */
        [HttpPost]
        public ActionResult Create(string new_story_title, string new_story_desc, string new_writer_username)
        {
            string queryString = "INSERT INTO stories (StoryTitle, StoryDescription, StoryCreator_WriterID, HasFeatureImage) VALUES (@stitle, @sdesc, @suser, @hasImg)";

            SqlParameter[] queryParams = new SqlParameter[4];
            queryParams[0] = new SqlParameter("@stitle", new_story_title);
            queryParams[1] = new SqlParameter("@sdesc", new_story_desc);
            queryParams[2] = new SqlParameter("@suser", new_writer_username);
            queryParams[3] = new SqlParameter("@hasImg", false);

            database.Database.ExecuteSqlCommand(queryString, queryParams);

            return RedirectToAction("GetList");
        }

        // Sends a viewmodel to the EditStory view for Story and returns the view
        // A viewmodel is used because the view needs information about both the story being 
        // edited and the writers in the database
        public ActionResult EditStory(int? id)
        {
            if ((id == null) || (database.Stories.Find(id) == null))
            {
                return HttpNotFound();
            }

            AddOrEditViewModel storyEditView = new AddOrEditViewModel();
            storyEditView.Story = database.Stories.Find(id);
            storyEditView.Writers = database.Writers.ToList();

            return View(storyEditView);
        }

        // This runs after the user submits a form to edit the story in the EditStory view
        // Updates the story in the database and adds/replaces an image if necessary
        [HttpPost]
        public ActionResult Update(int? id, string new_story_title, string new_story_desc, string new_writer_username, HttpPostedFileBase story_feature_image)
        {
            if ((id == null) || (database.Stories.Find(id) == null))
            {
                return HttpNotFound();
            }

            string query = "UPDATE stories SET StoryTitle=@stitle, StoryDescription=@sdesc, StoryCreator_WriterID=@screator WHERE StoryID=@storyid";

            SqlParameter[] queryParams = new SqlParameter[4];
            queryParams[0] = new SqlParameter("@stitle", new_story_title);
            queryParams[1] = new SqlParameter("@sdesc", new_story_desc);
            queryParams[2] = new SqlParameter("@screator", new_writer_username);
            queryParams[3] = new SqlParameter("@storyid", id);

            database.Database.ExecuteSqlCommand(query, queryParams);

            // Code to add an image follows Christine's Example
            if (story_feature_image != null)
            {
                //file extensioncheck taken from https://www.c-sharpcorner.com/article/file-upload-extension-validation-in-asp-net-mvc-and-javascript/
                var valtypes = new[] { "jpeg", "jpg", "png", "gif" };
                var extension = Path.GetExtension(story_feature_image.FileName).Substring(1);

                if (valtypes.Contains(extension))
                {
                    // Creates a filename that will be (id of story).(extension)
                    string filename = id + "." + extension;
                    string path = Path.Combine(Server.MapPath("~/images/featureImages"), filename);

                    // Save/Overwrite the image
                    story_feature_image.SaveAs(path);

                    // Update the fields for this story saying the story has a feature image, and save the extension
                    query = "UPDATE stories SET HasFeatureImage=@hasImg, ImageType=@ImgType WHERE StoryID=@storyid";

                    queryParams = new SqlParameter[3];
                    queryParams[0] = new SqlParameter("@hasImg", true);
                    queryParams[1] = new SqlParameter("@ImgType", extension);
                    queryParams[2] = new SqlParameter("@storyid", id);

                    database.Database.ExecuteSqlCommand(query, queryParams);
                }
            }

            return RedirectToAction("ViewStory/" + database.Stories.Find(id).StoryID);
        }

        // Delete all the story contents relating to this story and the story itself
        // Returns the GetList view for Story
        public ActionResult DeleteStory(int? id)
        {
            if ((id == null) || (database.Stories.Find(id) == null))
            {
                return HttpNotFound();
            }

            string queryString = "DELETE FROM storycontents WHERE Story_StoryID=@storyid";
            SqlParameter param = new SqlParameter("@storyid", id);

            database.Database.ExecuteSqlCommand(queryString, param);

            queryString = "DELETE FROM stories WHERE StoryID=@storyid";

            database.Database.ExecuteSqlCommand(queryString, param);

            return RedirectToAction("GetList");
        }

        // Returns the ViewStory view for the story corresponding to id
        public ActionResult ViewStory(int? id)
        {
            if ((id == null) || (database.Stories.Find(id) == null))
            {
                return HttpNotFound();
            }

            return View(database.Stories.Find(id));
        }

        // Returns the ReadStory view for the story corresponding to id
        public ActionResult ReadStory(int? id)
        {
            if ((id == null) || (database.Stories.Find(id) == null))
            {
                return HttpNotFound();
            }

            return View(database.Stories.Find(id));
        }
    }
}

StoryWriting_n01304390/Controllers/WriterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using StoryWriting_n01304390.Models;

namespace StoryWriting_n01304390.Controllers
{
    public class WriterController : Controller
    {
        private StoryWritingDbContext database = new StoryWritingDbContext();

        // Default View for Writer, redirect to the GetList View
        public ActionResult Index()
        {
            return RedirectToAction("GetList");
        }

        // Send a list of all writers to the GetList View for Writer and returns the view
        public ActionResult GetList()
        {
            IEnumerable<Writer> writers = database.Writers.ToList();
            return View(writers);
        }

        // Simply returns the AddWriter view
        public ActionResult AddWriter()
        {
            return View();
        }

        /* This runs after the user submits the form to add a writer in the view, add the writer to the database
            and redirect back to the GetList view */
        [HttpPost]
        public ActionResult Create(string new_writer_first_name, string new_writer_last_name, string new_writer_username)
        {
            string queryString = "INSERT INTO writers (FirstName, LastName, UserName) VALUES (@fname, @lname, @uname)";

            SqlParameter[] queryParams = new SqlParameter[3];
            queryParams[0] = new SqlParameter("@fname", new_writer_first_name);
            queryParams[1] = new SqlParameter("@lname", new_writer_last_name);
            queryParams[2] = new SqlParameter("@uname", new_writer_username);

            database.Database.ExecuteSqlCommand(queryString, queryParams);

            return RedirectToAction("GetList");
        }

        // Send the specific Writer model with corresponding with id to the EditWriter view and return the view
        public ActionResult EditWriter(int? id)
        {
            if ((id == null) || (database.Writers.Find(id) == null))
            {
                return HttpNotFound();
            }
            
            return View(database.Writers.Find(id));
        }

        /* This runs after the user submits the form to edit the writer in the view, update the writer to the database
            and redirect back to the view for the specific writer */
        [HttpPost]
        public ActionResult Update(int? id, string new_writer_first_name, string new_writer_last_name, string new_writer_username)
        {
            if ((id == null) || (database.Writers.Find(id) == null))
            {
                return HttpNotFound();
            }

            string query = "UPDATE writers SET FirstName=@fname, LastName=@lname, Username=@uname WHERE WriterID=@writerid";

            SqlParameter[] queryParams = new SqlParameter[4];
            queryParams[0] = new SqlParameter("@fname", new_writer_first_name);
            queryParams[1] = new SqlParameter("@lname", new_writer_last_name);
            queryParams[2] = new SqlParameter("@uname", new_writer_username);
            queryParams[3] = new SqlParameter("@writerid", id);

            database.Database.ExecuteSqlCommand(query, queryParams);

            return RedirectToAction("ViewWriter/" + database.Writers.Find(id).WriterID);
        }

        // Delete all the story contents and stories created by this writer, then delete the writer itself.
        // Returns the GetList view for Writer
        public ActionResult DeleteWriter(int? id)
        {
            if ((id == null) || (database.Writers.Find(id) == null))
            {
                return HttpNotFound();
            }

            string queryString = "DELETE FROM storycontents WHERE ContentWriter_WriterID=@writerid";
            SqlParameter param = new SqlParameter("@writerid", id);

            database.Database.ExecuteSqlCommand(queryString, param);

            queryString = "DELETE FROM stories WHERE StoryCreator_WriterID=@writerid";

            database.Database.ExecuteSqlCommand(queryString, param);

            queryString = "DELETE FROM writers WHERE WriterID=@writerid";

            database.Database.ExecuteSqlCommand(queryString, param);

            return RedirectToAction("GetList");
        }

        // Send the specific Writer model with corresponding with id to the ViewWriter view and return the view
        public ActionResult ViewWriter(int? id)
        {
            if ((id == null) || database.Writers.Find(id) == null)
            {
                return HttpNotFound();
            }

            return View(database.Writers.Find(id));
        }
    }
}

StoryWriting_n01304390/Views/Story/AddStory.cshtml
@model IEnumerable<StoryWriting_n01304390.Models.Writer>

@{
    ViewBag.Title = "AddStory";
}

<h2>Add a Story</h2>

<!-- Form to create a new story -->
<form method="POST" action="/Story/Create">
    <div class="form-row">
        <label for="story-title">Story Title:</label>
        <input type="text" id="story-title" name="new_story_title" />
    </div>
    <div class="form-row">
        <label for="story-desc">Story Description:</label>
        <textarea id="story-desc" name="new_story_desc" maxlength="1000"></textarea>
    </div>
    <div class="form-row">
        <label for="writer-username">Writer:</label>
        <select id="writer-username" name="new_writer_username">
            <!-- Creates a dropdown list with all the writers -->
            @foreach (var writer in Model)
            {
                <option value="@writer.WriterID">@writer.Username</option>
            }
        </select>
    </div>
    <div class="form-row">
        <input type="submit" value="Submit" />
    </div>
</form>

StoryWriting_n01304390/Views/Story/EditStory.cshtml
@model StoryWriting_n01304390.Models.ViewModels.AddOrEditViewModel

@{
    ViewBag.Title = "EditStory";
}

<h2>Edit Story</h2>

<!-- Form to edit an existing story -->
<form method="POST" action="/Story/Update/@Model.Story.StoryID" enctype="multipart/form-data">
    <div class="form-row">
        <label for="story-title">Story Title:</label>
        <input type="text" id="story-title" name="new_story_title" value="@Model.Story.StoryTitle" />
    </div>
    <div class="form-row">
        <h3>Feature Image: </h3>
        <!-- Displays the feature image if it exists -->
        @if (Model.Story.HasFeatureImage == true)
        {
            <div class="image-container">
                <img src="~/images/featureImages/@(Model.Story.StoryID).@(Model.Story.ImageType)" />
            </div>
        }
        else
        {
            <div>No Image</div>
        }
    </div>
    <div class="form-row">
        <label for="story-feature-image">Change Feature Image: </label>
        <input type="file" id="story-feature-image" name="story_feature_image" />
    </div>
    <div class="form-row">
        <label for="story-desc">Story Description:</label>
        <textarea id="story-desc" name="new_story_desc" maxlength="1000">@Model.Story.StoryDescription</textarea>
    </div>
    <div class="form-row">
        <label for="writer-username">Writer:</label>
        <select id="writer-username" name="new_writer_username">
            <!-- Creates a dropdown list with all the writers, current writer wil be selected -->
            @foreach (var writer in Model.Writers)
            {
                if (writer.Username == Model.Story.StoryCreator.Username)
                {
                    <option value="@writer.WriterID" selected>@writer.Username</option>
                }
                else
                {
                    <option value="@writer.WriterID">@writer.Username</option>
                }
            }
        </select>
    </div>
    <div class="form-row">
        <input type="submit" value="Submit" />
    </div>
</form>

StoryWriting_n01304390/Views/Story/GetList.cshtml
@model IEnumerable<StoryWriting_n01304390.Models.Story>

@{
    ViewBag.Title = "GetList";
}

<h2>Story List</h2>
<span class="link-area">@Html.ActionLink("Add a Story", "AddStory", "Story")</span>

<!-- Displays a list of all the stories in the database -->
<div class="flex-container">
    @foreach (var story in Model)
    {
        <div class="story-card">
            <div class="feat-image">
                @if (story.HasFeatureImage == true)
                {
                    <img src="~/images/featureImages/@(story.StoryID).@(story.ImageType)" alt="Story Feature Image" />
                }
                else
                {
                    <span>No Feature Image</span>
                }
            </div>
            <div class="story-info">
                <h3>@Html.ActionLink(story.StoryTitle, "ViewStory/" + story.StoryID, "Story")</h3>
                <span>Started By: @Html.ActionLink(story.StoryCreator.Username, "ViewWriter/" + story.StoryCreator.WriterID, "Writer")</span>
                <div>Description: @story.StoryDescription</div>

                <div>
                    @Html.ActionLink("Edit Story", "EditStory/" + story.StoryID, "Story") |
                    @Html.ActionLink("Delete Story", "DeleteStory/" + story.StoryID, "Story")
                </div>
            </div>
        </div>
    }
</div>

StoryWriting_n01304390/Views/Story/ReadStory.cshtml
@model StoryWriting_n01304390.Models.Story

@{
    ViewBag.Title = "ReadStory";
}

<h2>@Html.ActionLink(@Model.StoryTitle, "ViewStory/" + Model.StoryID, "Story")</h2>

<div>Story Description: @Model.StoryDescription</div>
<div>Story Creator: @Html.ActionLink(Model.StoryCreator.Username, "ViewWriter/" + Model.StoryCreator.WriterID, "Writer")</div>

@if (Model.HasFeatureImage == true)
{
    <div class="image-container">
        <img src="~/images/featureImages/@(Model.StoryID).@(Model.ImageType)" />
    </div>
}

<!-- Prints out all the contents relating to this story in one <p> -->
<p>
    @foreach (var content in Model.StoryContents)
    {
        <span>@content.Content </span>
    }
</p>

StoryWriting_n01304390/Views/Story/ViewStory.cshtml
@model StoryWriting_n01304390.Models.Story

@{
    ViewBag.Title = "ViewStory";
}

<h2>@Model.StoryTitle</h2>

<!-- Lists the information regarding the Story specified in the model, along with all the contents relating to this story
    in a table -->

<span class="link-area">@Html.ActionLink("Edit this Story", "EditStory/" + Model.StoryID, "Story")</span>
<span class="link-area">@Html.ActionLink("Delete this Story", "DeleteStory/" + Model.StoryID, "Story")</span>

<div>Story Description: @Model.StoryDescription</div>
<div>Story Creator: @Html.ActionLink(Model.StoryCreator.Username, "ViewWriter/" + Model.StoryCreator.WriterID, "Writer")</div>

@if (Model.HasFeatureImage == true)
{
    <div class="image-container">
        <img src="~/images/featureImages/@(Model.StoryID).@(Model.ImageType)" alt="Story Feature Image" />
    </div>
}

<h3>Story Content</h3>
<span class="link-area">@Html.ActionLink("Read Whole Story", "ReadStory/" + Model.StoryID, "Story")</span>
<span class="link-area">@Html.ActionLink("Add Content", "AddContent/" + Model.StoryID, "StoryContent")</span>

<table>
    <thead>
        <tr>
            <th>Content Writer</th>
            <th>Content</th>
            <th>Edit Content</th>
            <th>Delete Content</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var content in Model.StoryContents)
        {
            <tr>
                <td>@Html.ActionLink(content.ContentWriter.Username, "ViewWriter/" + content.ContentWriter.WriterID, "Writer")</td>
                <td>@content.Content</td>
                <td>@Html.ActionLink("Edit Content", "EditContent/" + content.StoryContentID, "StoryContent")</td>
                <td>@Html.ActionLink("Delete Content", "DeleteContent/" + content.StoryContentID, "StoryContent")</td>
            </tr>
        }
    </tbody>
</table>