StoryWriting_n01304390/Models/Writer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace StoryWriting_n01304390.Models
{
    // The model for a single writer
    // Has a writer id, first name, last name, and username
    // Links to multiple stories and multiple story contents
    public class Writer
    {
        [Key]
        public int WriterID { get; set; }

        [Required, StringLength(255), Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required, StringLength(255), Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required, StringLength(255), Display(Name = "Username")]
        public string Username { get; set; }

        public virtual ICollection<Story> Stories { get; set; }

        public virtual ICollection<StoryContent> StoryContents { get; set; }
    }
}

StoryWriting_n01304390/Controllers/StoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using StoryWriting_n01304390.Models;
using StoryWriting_n01304390.Models.ViewModels;
using System.IO;

namespace StoryWriting_n01304390.Controllers
{
    public class StoryController : Controller
    {
        private StoryWritingDbContext database = new StoryWritingDbContext();

        // Default View for Story, redirect to the GetList View
        public ActionResult Index()
        {
            return RedirectToAction("GetList");
        }

        // Send a list of all stories to the GetList View for Story and returns the view
        public ActionResult GetList()
        {
            IEnumerable<Story> stories = database.Stories.ToList();
            return View(stories);
        }

        // Send a list of all writers to the AddStory view for Story (used to generate the dropdown list) and return the view
        public ActionResult AddStory()
        {
            IEnumerable<Writer> writers = database.Writers.ToList();
            return View(writers);
        }

        /* This runs after the user submits the form to add a story in the view, add the story to the database
            and redirect back to the GetList view */
        [HttpPost]
        public ActionResult Create(string new_story_title, string new_story_desc, string new_writer_username)
        {
            string queryString = "INSERT INTO stories (StoryTitle, StoryDescription, StoryCreator_WriterID, HasFeatureImage) VALUES (@stitle, @sdesc, @suser, @hasImg)";

            SqlParameter[] queryParams = new SqlParameter[4];
            queryParams[0] = new SqlParameter("@stitle", new_story_title);
            queryParams[1] = new SqlParameter("@sdesc", new_story_desc);
            queryParams[2] = new SqlParameter("@suser", new_writer_username);
            queryParams[3] = new SqlParameter("@hasImg", false);

            database.Database.ExecuteSqlCommand(queryString, queryParams);

            return RedirectToAction("GetList");
        }

        // Sends a viewmodel to the EditStory view for Story and returns the view
        // A viewmodel is used because the view needs information about both the story being 
        // edited and the writers in the database
        public ActionResult EditStory(int? id)
        {
            if ((id == null) || (database.Stories.Find(id) == null))
            {
                return HttpNotFound();
            }

            AddOrEditViewModel storyEditView = new AddOrEditViewModel();
            storyEditView.Story = database.Stories.Find(id);
            storyEditView.Writers = database.Writers.ToList();

            return View(storyEditView);
        }

        // This runs after the user submits a form to edit the story in the EditStory view
        // Updates the story in the database and adds/replaces an image if necessary
        [HttpPost]
        public ActionResult Update(int? id, string new_story_title, string new_story_desc, string new_writer_username, HttpPostedFileBase story_feature_image)
        {
            if ((id == null) || (database.Stories.Find(id) == null))
            {
                return HttpNotFound();
            }

            string query = "UPDATE stories SET StoryTitle=@stitle, StoryDescription=@sdesc, StoryCreator_WriterID=@screator WHERE StoryID=@storyid";

            SqlParameter[] queryParams = new SqlParameter[4];
            queryParams[0] = new SqlParameter("@stitle", new_story_title);
            queryParams[1] = new SqlParameter("@sdesc", new_story_desc);
            queryParams[2] = new SqlParameter("@screator", new_writer_username);
            queryParams[3] = new SqlParameter("@storyid", id);

            database.Database.ExecuteSqlCommand(query, queryParams);

            // Code to add an image follows Christine's Example
            if (story_feature_image != null)
            {
                //file extensioncheck taken from https://www.c-sharpcorner.com/article/file-upload-extension-validation-in-asp-net-mvc-and-javascript/
                var valtypes = new[] { "jpeg", "jpg", "png", "gif" };
                var extension = Path.GetExtension(story_feature_image.FileName).Substring(1);

                if (valtypes.Contains(extension))
                {
                    // Creates a filename that will be (id of story).(extension)
                    string filename = id + "." + extension;
                    string path = Path.Combine(Server.MapPath("~/images/featureImages"), filename);

                    // Save/Overwrite the image
                    story_feature_image.SaveAs(path);

                    // Update the fields for this story saying the story has a feature image, and save the extension
                    query = "UPDATE stories SET HasFeatureImage=@hasImg, ImageType=@ImgType WHERE StoryID=@storyid";

                    queryParams = new SqlParameter[3];
                    queryParams[0] = new SqlParameter("@hasImg", true);
                    queryParams[1] = new SqlParameter("@ImgType", extension);
                    queryParams[2] = new SqlParameter("@storyid", id);

                    database.Database.ExecuteSqlCommand(query, queryParams);
                }
            }

            return RedirectToAction("ViewStory/" + database.Stories.Find(id).StoryID);
        }

        // Delete all the story contents relating to this story and the story itself
        // Returns the GetList view for Story
        public ActionResult DeleteStory(int? id)
        {
            if ((id == null) || (database.Stories.Find(id) == null))
            {
                return HttpNotFound();
            }

            string queryString = "DELETE FROM storycontents WHERE Story_StoryID=@storyid";
            SqlParameter param = new SqlParameter("@storyid", id);

            database.Database.ExecuteSqlCommand(queryString, param);

            queryString = "DELETE FROM stories WHERE StoryID=@storyid";

            database.Database.ExecuteSqlCommand(queryString, param);

            return RedirectToAction("GetList");
        }

        // Returns the ViewStory view for the story corresponding to id
        public ActionResult ViewStory(int? id)
        {
            if ((id == null) || (database.Stories.Find(id) == null))
            {
                return HttpNotFound();
            }

            return View(database.Stories.Find(id));
        }

        // Returns the ReadStory view for the story corresponding to id
        public ActionResult ReadStory(int? id)
        {
            if ((id == null) || (database.Stories.Find(id) == null))
            {
                return HttpNotFound();
            }

            return View(database.Stories.Find(id));
        }
    }
}

StoryWriting_n01304390/Controllers/WriterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using StoryWriting_n01304390.Models;

namespace StoryWriting_n01304390.Controllers
{
    public class WriterController : Controller
    {
        private StoryWritingDbContext database = new StoryWritingDbContext();

        // Default View for Writer, redirect to the GetList View
        public ActionResult Index()
        {
            return RedirectToAction("GetList");
        }

        // Send a list of all writers to the GetList View for Writer and returns the view
        public ActionResult GetList()
        {
            IEnumerable<Writer> writers = database.Writers.ToList();
            return View(writers);
        }

        // Simply returns the AddWriter view
        public ActionResult AddWriter()
        {
            return View();
        }

        /* This runs after the user submits the form to add a writer in the view, add the writer to the database
            and redirect back to the GetList view */
        [HttpPost]
        public ActionResult Create(string new_writer_first_name, string new_writer_last_name, string new_writer_username)
        {
            string queryString = "INSERT INTO writers (FirstName, LastName, UserName) VALUES (@fname, @lname, @uname)";

            SqlParameter[] queryParams = new SqlParameter[3];
            queryParams[0] = new SqlParameter("@fname", new_writer_first_name);
            queryParams[1] = new SqlParameter("@lname", new_writer_last_name);
            queryParams[2] = new SqlParameter("@uname", new_writer_username);

            database.Database.ExecuteSqlCommand(queryString, queryParams);

            return RedirectToAction("GetList");
        }

        // Send the specific Writer model with corresponding with id to the EditWriter view and return the view
        public ActionResult EditWriter(int? id)
        {
            if ((id == null) || (database.Writers.Find(id) == null))
            {
                return HttpNotFound();
            }
            
            return View(database.Writers.Find(id));
        }

        /* This runs after the user submits the form to edit the writer in the view, update the writer to the database
            and redirect back to the view for the specific writer */
        [HttpPost]
        public ActionResult Update(int? id, string new_writer_first_name, string new_writer_last_name, string new_writer_username)
        {
            if ((id == null) || (database.Writers.Find(id) == null))
            {
                return HttpNotFound();
            }

            string query = "UPDATE writers SET FirstName=@fname, LastName=@lname, Username=@uname WHERE WriterID=@writerid";

            SqlParameter[] queryParams = new SqlParameter[4];
            queryParams[0] = new SqlParameter("@fname", new_writer_first_name);
            queryParams[1] = new SqlParameter("@lname", new_writer_last_name);
            queryParams[2] = new SqlParameter("@uname", new_writer_username);
            queryParams[3] = new SqlParameter("@writerid", id);

            database.Database.ExecuteSqlCommand(query, queryParams);

            return RedirectToAction("ViewWriter/" + database.Writers.Find(id).WriterID);
        }

        // Delete all the story contents and stories created by this writer, then delete the writer itself.
        // Returns the GetList view for Writer
        public ActionResult DeleteWriter(int? id)
        {
            if ((id == null) || (database.Writers.Find(id) == null))
            {
                return HttpNotFound();
            }

            string queryString = "DELETE FROM storycontents WHERE ContentWriter_WriterID=@writerid";
            SqlParameter param = new SqlParameter("@writerid", id);

            database.Database.ExecuteSqlCommand(queryString, param);

            queryString = "DELETE FROM stories WHERE StoryCreator_WriterID=@writerid";

            database.Database.ExecuteSqlCommand(queryString, param);

            queryString = "DELETE FROM writers WHERE WriterID=@writerid";

            database.Database.ExecuteSqlCommand(queryString, param);

            return RedirectToAction("GetList");
        }

        // Send the specific Writer model with corresponding with id to the ViewWriter view and return the view
        public ActionResult ViewWriter(int? id)
        {
            if ((id == null) || database.Writers.Find(id) == null)
            {
                return HttpNotFound();
            }

            return View(database.Writers.Find(id));
        }
    }
}

StoryWriting_n01304390/Views/Writer/AddWriter.cshtml
@{
    ViewBag.Title = "AddWriter";
}

<h2>Add a Writer</h2>

<!-- Form to add a new writer -->
<form method="POST" action="/Writer/Create">
    <div class="form-row">
        <label for="writer-first-name">First Name:</label>
        <input type="text" id="writer-first-name" name="new_writer_first_name" />
    </div>
    <div class="form-row">
        <label for="writer-last-name">Last Name:</label>
        <input type="text" id="writer-last-name" name="new_writer_last_name" />
    </div>
    <div class="form-row">
        <label for="writer-username">Username:</label>
        <input type="text" id="writer-username" name="new_writer_username" />
    </div>
    <div class="form-row">
        <input type="submit" value="Submit" />
    </div>
</form>

StoryWriting_n01304390/Views/Writer/EditWriter.cshtml
@model StoryWriting_n01304390.Models.Writer

@{
    ViewBag.Title = "EditWriter";
}

<h2>Edit Writer</h2>

<!-- Form to edit an existing writer -->
<form method="POST" action="/Writer/Update/@Model.WriterID">
    <div class="form-row">
        <label for="writer-first-name">First Name:</label>
        <input type="text" id="writer-first-name" name="new_writer_first_name" value="@Model.FirstName" />
    </div>
    <div class="form-row">
        <label for="writer-last-name">Last Name:</label>
        <input type="text" id="writer-last-name" name="new_writer_last_name" value="@Model.LastName" />
    </div>
    <div class="form-row">
        <label for="writer-username">Username:</label>
        <input type="text" id="writer-username" name="new_writer_username" value="@Model.Username" />
    </div>
    <div class="form-row">
        <input type="submit" value="Submit" />
    </div>
</form>

StoryWriting_n01304390/Views/Writer/GetList.cshtml
@model IEnumerable<StoryWriting_n01304390.Models.Writer>

@{
    ViewBag.Title = "GetList";
}

<h2>Writer List</h2>
<span class="link-area">@Html.ActionLink("Add a Writer", "AddWriter", "Writer")</span>

<!-- Display a list of all writers in the database -->
<div class="flex-container">
    @foreach (var writer in Model)
    {
        <div class="writer-card">
            <h3>@Html.ActionLink(writer.Username, "ViewWriter/" + writer.WriterID, "Writer")</h3>
            <span>@writer.FirstName @writer.LastName</span>
            <div>
                @Html.ActionLink("Edit Writer", "EditWriter/" + writer.WriterID, "Writer") | 
                @Html.ActionLink("Delete Writer", "DeleteWriter/" + writer.WriterID, "Writer")
            </div>
        </div>
    }
</div>

StoryWriting_n01304390/Views/Writer/ViewWriter.cshtml
@model StoryWriting_n01304390.Models.Writer

@{
    ViewBag.Title = "ViewWriter";
}

<h2>@Model.Username</h2>
<!-- Display information about the specific writer specified in the model -->

<span class="link-area">@Html.ActionLink("Edit this Writer", "EditWriter/" + Model.WriterID, "Writer")</span>
<span class="link-area">@Html.ActionLink("Delete this Writer", "DeleteWriter/" + Model.WriterID, "Writer")</span>

<div class="info-area">
    <div>First Name: @Model.FirstName</div>
    <div>Last Name: @Model.LastName</div>
</div>

<h3>Stories Started: </h3>
<ul>
    @foreach (var story in Model.Stories)
    {
        <li>@Html.ActionLink(story.StoryTitle, "ViewStory/" + story.StoryID, "Story")</li>
    }
</ul>